python tools/train_net.py --config-file=configs/gpt2_pretrain.py \
      graph.enabled=False \
      train.train_micro_batch_size=4 \
      train.train_epoch=1 \
      train.train_iter=8 \
      train.num_accumulation_steps=1 \
      train.input_placement_device="xpu" \
      train.dist.device_type="xpu" \
      train.amp.enabled=False \
      train.evaluation.enabled=False \
      train.log_period=1 \
      train.dist.data_parallel_size=1 \
      train.dist.tensor_parallel_size=1 \
      train.dist.pipeline_parallel_size=1 \
      train.train_micro_batch_size=1 \
      train.evaluation.enabled=False \
      train.checkpointer.period=100000000000 \
      train.checkpointer.max_to_keep=1 \
      optim.lr=1e-5 \
      model.cfg.scale_mask_softmax_fusion=False \
      model.cfg.bias_dropout_fusion=False \
      model.cfg.bias_gelu_fusion=False
